version: '3'

services:
  monero_miner:
    image: praetor207/xmrig:amd
    env_file:
      - /home/wfisher/.env
    environment:
      - COIN=monero
      - POOL=stratum+tcp://xmr-us-east1.nanopool.org:10300
      - WALLET=42Vwghfqz3NAZYy4D83Hn7AcMSoQTpV6hAtWzjseQiZxQwQt3HT24ryJgwrFVvWKrXAcvRah8avGuKiK9tz5Mu8P1QdCShq.cloud9/praetor207@gmail.com
      - PASSWORD=M@ck3y242
    container_name: monero_miner
    devices:
      - /dev/dri:/dev/dri

