version: '3'

services:
  monero_miner:
    image: praetor207/xmrig:nvidia
    env_file:
      - /home/wfisher/.env
    container_name: monero_miner
    runtime: nvidia
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia0
